### ISSUE TITLE
context_feature stand for?

### ISSUE THREAD

**Issue by anhnh2002** [chenlong-clock/CFED-HANet#1]
Does context_feature stand for h_CLS (hidden state of CLS token)?
<img width="974" alt="Screenshot 2024-06-25 at 18 23 15" src="https://github.com/chenlong-clock/CFED-HANet/assets/79850337/3d7dc733-5cb2-48c4-879e-16df2108ac0c">

**Comment by chenlong-clock** [comment]
No, the context feature is the output feature from BERT, used for feature distillation.

**Comment by anhnh2002** [comment]
Thank @chenlong-clock . Another question
Below is one sample in MAVEN dataset
```
{'piece_ids': [101,
  1996,
  2265,
  2001,
  4055,
  2046,
  2698,
  9214,
  2007,
  1996,
  2197,
  2028,
  2108,
  1996,
  19493,
  1012,
  102],
 'label': [83, 0, 0, 0],
 'span': [[2, 2], [10, 10], [7, 7], [14, 14]],
 'sentence_id': '67ef13149798917c9c20f2744f339b57_10',
 'mention_id': ['cff1ffd70cf7fecd0bbbb75675601cdc',
  'a6db1fbc3005313fa7f6403156325eb2',
  'a35cc646e8291d01fa18a9f1a4cae6fc',
  '10d7494369efb1b944a832f711652217']}
```
Can you explain 'label', 'span', 'sentence_id', 'mention_id' for me?
Thank you so much!

**Comment by chenlong-clock** [comment]
> Thank @chenlong-clock . Another question Below is one sample in MAVEN dataset
> 
> ```
> {'piece_ids': [101,
>   1996,
>   2265,
>   2001,
>   4055,
>   2046,
>   2698,
>   9214,
>   2007,
>   1996,
>   2197,
>   2028,
>   2108,
>   1996,
>   19493,
>   1012,
>   102],
>  'label': [83, 0, 0, 0],
>  'span': [[2, 2], [10, 10], [7, 7], [14, 14]],
>  'sentence_id': '67ef13149798917c9c20f2744f339b57_10',
>  'mention_id': ['cff1ffd70cf7fecd0bbbb75675601cdc',
>   'a6db1fbc3005313fa7f6403156325eb2',
>   'a35cc646e8291d01fa18a9f1a4cae6fc',
>   '10d7494369efb1b944a832f711652217']}
> ```
> 
> Can you explain 'label', 'span', 'sentence_id', 'mention_id' for me? Thank you so much!

label: event type id. 'span': the span position of the event triggers. The sentence_id and mention originate from the initial MAVEN dataset. You can find detailed information from the MAVEN's official repo. Good luck!
If you find our code helpful, please consider giving it a star~

**Comment by anhnh2002** [comment]
> > Thank @chenlong-clock . Another question Below is one sample in MAVEN dataset
> 
> > 
> 
> > ```
> 
> > {'piece_ids': [101,
> 
> >   1996,
> 
> >   2265,
> 
> >   2001,
> 
> >   4055,
> 
> >   2046,
> 
> >   2698,
> 
> >   9214,
> 
> >   2007,
> 
> >   1996,
> 
> >   2197,
> 
> >   2028,
> 
> >   2108,
> 
> >   1996,
> 
> >   19493,
> 
> >   1012,
> 
> >   102],
> 
> >  'label': [83, 0, 0, 0],
> 
> >  'span': [[2, 2], [10, 10], [7, 7], [14, 14]],
> 
> >  'sentence_id': '67ef13149798917c9c20f2744f339b57_10',
> 
> >  'mention_id': ['cff1ffd70cf7fecd0bbbb75675601cdc',
> 
> >   'a6db1fbc3005313fa7f6403156325eb2',
> 
> >   'a35cc646e8291d01fa18a9f1a4cae6fc',
> 
> >   '10d7494369efb1b944a832f711652217']}
> 
> > ```
> 
> > 
> 
> > Can you explain 'label', 'span', 'sentence_id', 'mention_id' for me? Thank you so much!
> 
> 
> 
> label: event type id. 'span': the span position of the event triggers. The sentence_id and mention originate from the initial MAVEN dataset. You can find detailed information from the MAVEN's official repo. Good luck!
> 
> If you find our code helpful, please consider giving it a star~

I see number of span (= number of label) equal to number of piece_ids (ignore CLS and SEP token) in ACE dataset. It difference from MAVEN dataset. Why?

And why span in [x,x] format instead of x?

**Comment by chenlong-clock** [comment]
> I see number of span (= number of label) equal to number of piece_ids (ignore CLS and SEP token) in ACE dataset. It difference from MAVEN dataset. Why?

Because ACE dataset does not label the event triggers. We regard all the spans as the candidate event triggers.

> And why span in [x,x] format instead of x?

In MAVEN annotations, an event trigger may contain one or multiple spans, [x, x] indicates the event is triggered by a single token.

**Comment by Kohhh24** [comment]
I apologize for any inconvenience. I have executed the code using the hyperparameters as specified in the paper and the accompanying code. However, the accuracy results I am obtaining consistently fall short of the benchmarks provided in the paper. For instance, the microF1 score during the second stage of the 2-way 5-shot evaluation on the ACE dataset is lower by 10-20 percentage points compared to the values reported in the paper. Could there be a reason for this discrepancy? Is it possible that some code or hyperparameters have not been updated or are not in sync with the latest findings?
I have uploaded the log file for the 'ACE/none/10class/5shot/shuffle_r1/perm0' experiment in the attachment. Could you please review it? I would appreciate your insights on any potential issues or discrepancies that might be affecting the accuracy of the results.
[2024-06-27-22-17-20.log](https://github.com/user-attachments/files/16015758/2024-06-27-22-17-20.log)
