### ISSUE TITLE
Could you provide the code that preprocesses the MAVEN and ACE datasets?

### ISSUE THREAD

**Issue by anhnh2002** [chenlong-clock/CFED-HANet#4]

**Comment by chenlong-clock** [comment]
I directly use the preprocessed data from [Lifelong Event Detection with Knowledge Transfer](https://aclanthology.org/2021.emnlp-main.428). You can check their datasets in the [repo](https://github.com/Perfec-Yu/Lifelong-ED/tree/main/data) for details.

**Comment by anhnh2002** [comment]
> I directly use the preprocessed data from [Lifelong Event Detection with Knowledge Transfer](https://aclanthology.org/2021.emnlp-main.428). You can check their datasets in the [repo](https://github.com/Perfec-Yu/Lifelong-ED/tree/main/data) for details.

Thank you.
